### ISSUE TITLE
Door bug

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-Drop2Inventory#5]
If I break the iron door with the magical digging of the silky touch, it comes down on me and it falls to the ground so I have 2 doors.

http://prntscr.com/mj1ke4

it doesn't come over when some doors a normal pickaxe break.
http://prntscr.com/mj1ktt

**Comment by mfnalex** [comment]
Thank you, this has been added to my todo-list.

**Comment by mfnalex** [comment]
Has been fixed as of version 3.2 :)

**Comment by successed** [comment]
> Has been fixed as of version 3.2 :)

this not fixed,When the door breaks, it doesn't come into the inventory.

**Comment by successed** [comment]
> Has been fixed as of version 3.2 :)

Thanks
